# Generated by Django 4.0.8 on 2022-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostTypeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type_class_code', models.CharField(max_length=2, unique=True, verbose_name='Cost Type Class Code')),
                ('cost_type_class_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Cost Type Class Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Cost Type Classes',
                'db_table': 'cost_type_class',
                'ordering': ['cost_type_class_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=5, unique=True, verbose_name='Department Code')),
                ('department_title', models.CharField(max_length=55, unique=True, verbose_name='Department Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['department_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_code', models.CharField(max_length=5, unique=True, verbose_name='Discipline Code')),
                ('discipline_title', models.CharField(max_length=55, unique=True, verbose_name='Discipline Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Disciplines',
                'db_table': 'discipline',
                'ordering': ['discipline_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacilitySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_system_code', models.CharField(max_length=5, unique=True, verbose_name='Facility System Code')),
                ('facility_system_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Facility System Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Facility Systems',
                'db_table': 'facility_system',
                'ordering': ['facility_system_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmbWpStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmb_wp_status_code', models.CharField(max_length=5, unique=True, verbose_name='PMB WP Status Code')),
                ('pmb_wp_status_title', models.CharField(max_length=55, unique=True, verbose_name='PMB WP Status Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'PMB WP Status Types',
                'db_table': 'pmb_wp_status_type',
                'ordering': ['pmb_wp_status_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabWpExecutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_wp_exe_type_code', models.CharField(max_length=5, unique=True, verbose_name='TAB WP Execution Type Code')),
                ('tab_wp_exe_type_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='TAB WP Execution Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'TAB WP Execution Types',
                'db_table': 'tab_wp_exe_type',
                'ordering': ['tab_wp_exe_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabWpStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_wp_status_code', models.CharField(max_length=5, unique=True, verbose_name='TAB WP Status Code')),
                ('tab_wp_status_title', models.CharField(max_length=55, unique=True, verbose_name='TAB WP Status Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'TAB WP Status Types',
                'db_table': 'tab_wp_status_type',
                'ordering': ['tab_wp_status_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WBSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_type_code', models.CharField(max_length=5, unique=True, verbose_name='WBS Type Code')),
                ('wbs_type_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='WBS Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'WBS Types',
                'db_table': 'wbs_type',
                'ordering': ['wbs_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type_code', models.CharField(max_length=5, unique=True, verbose_name='Cost Type Code')),
                ('cost_type_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Cost Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cost_type_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.costtypeclass', verbose_name='Cost Type Class ID')),
            ],
            options={
                'verbose_name_plural': 'Cost Types',
                'db_table': 'cost_type',
                'ordering': ['cost_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_code', models.CharField(max_length=5, unique=True, verbose_name='WBS Code')),
                ('wbs_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='WBS Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('wbs_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.wbstype', verbose_name='WBS Type ID')),
            ],
            options={
                'verbose_name_plural': 'WBS',
                'db_table': 'wbs',
                'ordering': ['wbs_code'],
                'managed': True,
                'unique_together': {('wbs_type', 'wbs_code')},
            },
        ),
        migrations.CreateModel(
            name='PmbWpExecutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmb_wp_exe_type_code', models.CharField(max_length=5, unique=True, verbose_name='PMB WP Execution Type Code')),
                ('pmb_wp_exe_type_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='PMB WP Execution Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('tab_wp_exe_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.tabwpexecutiontype', verbose_name='TAB WP Execution Type ID')),
            ],
            options={
                'verbose_name_plural': 'PMB WP Execution Types',
                'db_table': 'pmb_wp_exe_type',
                'ordering': ['pmb_wp_exe_type_code'],
                'managed': True,
                'unique_together': {('tab_wp_exe_type', 'pmb_wp_exe_type_code')},
            },
        ),
        migrations.CreateModel(
            name='FacilitySystemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_system_detail_code', models.CharField(max_length=15, unique=True, verbose_name='Facility System Detail Code')),
                ('facility_system_detail_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Facility System Detail Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('facility_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.facilitysystem', verbose_name='Facility System ID')),
            ],
            options={
                'verbose_name_plural': 'Facility System Details',
                'db_table': 'facility_system_detail',
                'ordering': ['facility_system_detail_code'],
                'managed': True,
                'unique_together': {('facility_system', 'facility_system_detail_code')},
            },
        ),
    ]
