# Generated by Django 4.0.8 on 2022-12-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_wbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costtype',
            name='cost_type_class',
        ),
    ]
