# Generated by Django 4.0.8 on 2022-12-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_wbs', '0002_remove_costtype_cost_type_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtype',
            name='cost_type_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cost Type Code'),
        ),
        migrations.AlterField(
            model_name='costtypeclass',
            name='cost_type_class_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cost Type Class Code'),
        ),
    ]
