# Generated by Django 4.0.8 on 2022-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_wbs', '0003_alter_costtype_cost_type_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtype',
            name='cost_type_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cost Type Code'),
        ),
    ]
