# Generated by Django 4.0.8 on 2023-01-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_wbs', '0004_alter_costtype_cost_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='cost_type_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.costtypeclass', verbose_name='Cost Type Class ID'),
        ),
    ]
