# Generated by Django 4.0.8 on 2023-01-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_tab_pmb_quantum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmbwpcal04quantum',
            name='uom',
        ),
    ]
