# Generated by Django 4.0.8 on 2023-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_tab_pmb_quantum', '0002_remove_pmbwpcal04quantum_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmbwpcal04',
            name='cfb_costs',
        ),
        migrations.RemoveField(
            model_name='pmbwpcal04',
            name='cfb_hours',
        ),
        migrations.RemoveField(
            model_name='pmbwpcal04',
            name='cfb_quantity',
        ),
        migrations.RemoveField(
            model_name='pmbwpcal04quantum',
            name='cfb_quantity',
        ),
        migrations.AddField(
            model_name='pmbwpcal04',
            name='bac_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='BAC Costs'),
        ),
        migrations.AddField(
            model_name='pmbwpcal04',
            name='bac_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='BAC Hours'),
        ),
        migrations.AddField(
            model_name='pmbwpcal04',
            name='bac_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='BAC Quantity'),
        ),
        migrations.AddField(
            model_name='pmbwpcal04quantum',
            name='bac_quantum_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='BAC Quantum Quantity'),
        ),
    ]
