# Generated by Django 4.0.8 on 2023-01-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_hr', '0002_alter_stakeholderroles_stakeholder_role_code_and_more'),
        ('z_tab_pmb_quantum', '0003_remove_pmbwpcal04_cfb_costs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmbwpcal03',
            name='cost_type_class',
        ),
        migrations.AddField(
            model_name='pmbwpcal03',
            name='stakeholder_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_hr.stakeholderroles', verbose_name='Stakeholder Role ID'),
        ),
    ]
