# Generated by Django 4.0.8 on 2022-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('z_tab_pmb_quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmbWpCaL04AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField(verbose_name='Calendar Date')),
                ('ar_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3)),
                ('ar_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Accounts Receivable Costs on Calendar Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('pmb_wp_ca_L04', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_tab_pmb_quantum.pmbwpcal04', verbose_name='PMB WP CA L04 ID')),
            ],
            options={
                'verbose_name_plural': 'PMB WP CA L04 Accounts Receivable',
                'db_table': 'pmb_wp_ca_L04_ar',
                'ordering': ['pmb_wp_ca_L04', 'calendar_date'],
                'managed': True,
                'unique_together': {('pmb_wp_ca_L04', 'calendar_date')},
            },
        ),
        migrations.CreateModel(
            name='PmbWpCaL04AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField(verbose_name='Calendar Date')),
                ('ap_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3)),
                ('ap_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Accounts Payable Costs on Calendar Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('pmb_wp_ca_L04', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_tab_pmb_quantum.pmbwpcal04', verbose_name='PMB WP CA L04 ID')),
            ],
            options={
                'verbose_name_plural': 'PMB WP CA L04 Accounts Payable',
                'db_table': 'pmb_wp_ca_L04_ap',
                'ordering': ['pmb_wp_ca_L04', 'calendar_date'],
                'managed': True,
                'unique_together': {('pmb_wp_ca_L04', 'calendar_date')},
            },
        ),
    ]
