# Generated by Django 4.0.8 on 2022-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TABSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_schedule_code', models.CharField(max_length=55, unique=True, verbose_name='TAB Schedule Code')),
                ('tab_schedule_title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='TAB Schedule Title')),
                ('early_start_date', models.DateTimeField(blank=True, null=True, verbose_name='TAB Early Start Date')),
                ('early_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='TAB Early Finish Date')),
                ('early_start_to_early_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='TAB Early Start to Early Finish Duration')),
                ('late_start_date', models.DateTimeField(blank=True, null=True, verbose_name='TAB Late Start Date')),
                ('late_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='TAB Late Finish Date')),
                ('late_start_to_late_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='TAB Late Start to Late Finish Duration')),
                ('critical_path_check', models.IntegerField(default=0, verbose_name='TAB Critical Path Check')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='TAB Comments')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.discipline', verbose_name='Discipline Code')),
                ('tab_wp_exe_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.pmbwpexecutiontype', verbose_name='TAB Type Code')),
            ],
            options={
                'verbose_name_plural': 'TAB aka EB aka L03 Schedule',
                'db_table': 'tab_schedule',
                'ordering': ['tab_schedule_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PMBSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmb_schedule_code', models.CharField(max_length=55, unique=True, verbose_name='CB Schedule Code')),
                ('pmb_schedule_title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CB Schedule Title')),
                ('early_start_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Early Start Date')),
                ('early_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Early Finish Date')),
                ('early_start_to_early_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='CB Early Start to Early Finish Duration')),
                ('late_start_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Late Start Date')),
                ('late_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Late Finish Date')),
                ('late_start_to_late_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='CB Late Start to Late Finish Duration')),
                ('critical_path_check', models.IntegerField(default=0, verbose_name='CB Critical Path Check')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CB Comments')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.discipline', verbose_name='Discipline Code')),
                ('pmb_wp_exe_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.pmbwpexecutiontype', verbose_name='PMB Type Code')),
                ('tab_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_schedules.tabschedule', verbose_name='TAB Schedule Code')),
            ],
            options={
                'verbose_name_plural': 'PMB aka CB aka L04 Schedule',
                'db_table': 'pmb_schedule',
                'ordering': ['pmb_schedule_code'],
                'managed': True,
            },
        ),
    ]
