# Generated by Django 4.0.8 on 2022-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('z_tab_pmb_quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmbWpCaL04Actuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField(verbose_name='Calendar Date')),
                ('forecast_actual_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Forecasted Actuals Hours on Calendar Date')),
                ('forecast_actual_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3)),
                ('forecast_actual_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Forecasted Actuals Costs on Calendar Date')),
                ('incurred_actual_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Incurred Actuals Hours on Calendar Date')),
                ('incurred_actual_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3)),
                ('incurred_actual_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Incurred Actuals Costs on Calendar Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('pmb_wp_ca_L04', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_tab_pmb_quantum.pmbwpcal04', verbose_name='PMB WP CA L04 ID')),
            ],
            options={
                'verbose_name_plural': 'PMB WP CA L04 Actuals',
                'db_table': 'pmb_wp_ca_L04_actuals',
                'ordering': ['pmb_wp_ca_L04', 'calendar_date'],
                'managed': True,
                'unique_together': {('pmb_wp_ca_L04', 'calendar_date')},
            },
        ),
    ]
