# Generated by Django 4.0.8 on 2023-01-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderroles',
            name='stakeholder_role_code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Stakeholder Role Code'),
        ),
        migrations.AlterField(
            model_name='stakeholderroles',
            name='stakeholder_role_title',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Stakeholder Role Title'),
        ),
    ]
